name: Validate
on:
  push:
    branches:
      - main

jobs:
  validate:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Install python packages (pip)"
        run: pip install -r requirements.txt
      
      - run: mkdir results

      - run: python stac_api_validator/validate.py --root https://tamn.snapplanet.io --no-post > results/resto.txt || true
      - run: python stac_api_validator/validate.py --root https://planetarycomputer.microsoft.com/api/stac/v1 > results/stac-fastapi-pc.txt || true
      - run: python stac_api_validator/validate.py --root https://cmr.earthdata.nasa.gov/stac/USGS_EROS > results/stac-cmr-earthdata.txt || true
      - run: python stac_api_validator/validate.py --root https://franklin.nasa-hsi.azavea.com > results/franklin.txt || true
      - run: python stac_api_validator/validate.py --root https://explorer.digitalearth.africa/stac/ > results/digitalearth_africa.txt || true
      - run: python stac_api_validator/validate.py --root https://staccato.space > results/staccato.txt || true
      - run: python stac_api_validator/validate.py --root https://eod-catalog-svc-prod.astraea.earth > results/astraea.txt || true

      - name: Archive validation results
        uses: actions/upload-artifact@v2
        with:
          name: validation-results
          path: |
            results

      - run: echo "Successfully run."
